### ISSUE TITLE
program failed

### ISSUE THREAD

**Issue by lmanchon** [babelomics/ngscat2#3]
--Hi,

runnning: 
ngscat2 --bams ./SRR6823381.bam --bed ./Exome-Agilent.bed --out /work/ngscat --reference ./Homo_sapiens_hg38.fasta

it failed with:

Traceback (most recent call last):
  File "ngscat2", line 8, in <module>
    sys.exit(main())
  File "main.py", line 416, in main
    generate_report(options, config)
  File "/.local/lib/python3.7/site-packages/ngscat2/main.py", line 290, in generate_report
    cover, _ = bam.myCoverageBed(options.bed, bedGraphFile=mainReporter.outdir)
  File "/.local/lib/python3.7/site-packages/ngscat2/misc/bam_file.py", line 518, in myCoverageBed
    endPositions.append(int(currentRead.aend))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

how to identify the problem?
thank you --

**Comment by Alnkhife** [comment]
i'm getting the same issue, any help is appreciated.

Best,
